"""add computed full_invoice_number

Revision ID: 1c5616b674a5
Revises: ddd1745150eb
Create Date: 2025-12-03 13:58:55.931011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5616b674a5'
down_revision: Union[str, Sequence[str], None] = 'ddd1745150eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices_rls', sa.Column('invoice_number', sa.String(), sa.Computed('invoice_prefix || invoice_sequence::text', persisted=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices_rls', 'invoice_number')
    # ### end Alembic commands ###
