"""add paymentdate

Revision ID: d48533e2bc00
Revises: 1c5616b674a5
Create Date: 2025-12-03 15:02:04.227462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd48533e2bc00'
down_revision: Union[str, Sequence[str], None] = '1c5616b674a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments_rls', sa.Column('payment_date', sa.DateTime(), nullable=False))
    op.drop_column('payments_rls', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments_rls', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('payments_rls', 'payment_date')
    # ### end Alembic commands ###
